### ISSUE TITLE
Fingerprinting failed: audio could not be decoded

### ISSUE THREAD

**Issue by bolisaf** [beetbox/pyacoustid#30]
running beets on ubuntu, installed using 'pip install beets'.
I've a problem where Gstreamer is unable to decode MP3 files, but it does encode m4a files. this means there is a problem with the 'ugly' plugin. I've tried reinstalling both beets and gstreamer to no avail. it's not the mp3 itself, i can play it. i have the problem (and same errors) on all mp3s. 

`$ beet import /mnt/2TERRA/musictoimport/005\ Doormouse/
/usr/local/lib/python2.7/dist-packages/audioread/gstdec.py:126: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
/usr/local/lib/python2.7/dist-packages/audioread/gstdec.py:146: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use GLib.MainLoop instead
  self.loop = GObject.MainLoop()
chroma: fingerprinting of '/mnt/2TERRA/musictoimport/005 Doormouse/[A1] Doormouse - Toxic Jungle.mp3' failed: audio could not be decoded
chroma: fingerprinting of '/mnt/2TERRA/musictoimport/005 Doormouse/[A2] Doormouse - Six Million More.mp3' failed: audio could not be decoded
chroma: fingerprinting of '/mnt/2TERRA/musictoimport/005 Doormouse/[B1] Doormouse - Doormanymouse.mp3' failed: audio could not be decoded
chroma: fingerprinting of '/mnt/2TERRA/musictoimport/005 Doormouse/[B2] Doormouse - A Real Winner.mp3' failed: audio could not be decoded
`

**Comment by sampsyo** [comment]
Hey! Did you mean to close this issue?

Also, could you please provide a lot more detail about your system? Which Ubuntu version, and exactly which packages are installed?

It would also be awesome if you could try reproducing this by running the pyacoustid script (`aidmatch.py`) directly.
