### ISSUE TITLE
1.1.5 release

### ISSUE THREAD

**Issue by regagain** [beetbox/pyacoustid#35]
Hi!

The changelog mentions a 1.1.5 version that includes #33, but there is no 1.1.5 release on the release page (https://github.com/beetbox/pyacoustid/releases).

This is preventing, for example, this Arch/Parabola AUR to pick the latest version: https://aur.archlinux.org/packages/python-pyacoustid/

Can you please make a release for 1.1.5?

Thanks!

**Comment by sampsyo** [comment]
Hi! I usually build up a release in the changelog before it's done, and then actually publish a release along with each new beets version. But since you asked, I've tagged and pushed v1.1.5 to PyPI. Enjoy! :sparkles:

**Comment by regagain** [comment]
Thanks a lot :) Now I can submit fingerprints from beets again =]
