### ISSUE TITLE
Genre of a track

### ISSUE THREAD

**Issue by polochinoc** [beetbox/pyacoustid#42]
Hello everyone, I used this module to get the fingerprint and duration of my songs, then sending it through a POST request to Acoustid API, but I still haven't managed to get the genre of a song if it exists. I can't get tags with 'meta' attribute, 'meta=recordings+releases' give me quite some information, but I just need one more info which is the genre. So if you have any ideas, I'd be happy to hear them :)

Thank you for your time, Paul

**Comment by sampsyo** [comment]
Hi! The Acoustid database does not contain genres. (Neither does MusicBrainz.) Maybe you're thinking of the similarly-named [AcousticBrainz](https://acousticbrainz.org)?
