### ISSUE TITLE
Chromaprint library/tool not found

### ISSUE THREAD

**Issue by RajHarry** [beetbox/pyacoustid#44]
while Running **"aidmatch.py"**,
I got above error....Help In this...
thanks in advance

**Comment by arcresu** [comment]
You need to install chromaprint before you can use pyacoutid. There are instructions [in the readme](https://github.com/beetbox/pyacoustid#installation) of this project. If you find a specific problem, or the instructions are unclear, please open a new bug report with more information and we'll see what we can do.
