### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by fpom** [beetbox/pyacoustid#45]
I'm using acoustid.fingerprint_file() repeatedly on a collection of MP3 files, and I see the memory usage of my script growing over and over despite the fact I store the obtained fingerprints in a DBM. (I've done the same with SHA512 hashes and I observed no such increasing memory usage).

So I strongly suspect a memory leak in the library.

I've installed 1.1.5 with pip, using Python 3.6.2 under Linux.

**Comment by sampsyo** [comment]
Hi! Any chance you’re using GStreamer? If so, we may have just fixed the problem in audioread: https://github.com/beetbox/audioread/pull/84

**Comment by fpom** [comment]
I have no idea whether I'm using GStreamer or not. How can I check? I just do: `import acoustid` then `acoustid.fingerprint_file(somepath)`.

BTW, I've replaced `acoustid.fingerprint_file()` with `subprocess.check_output(["fpcalc", ...])` and it's much faster, which surprised me.

**Comment by sampsyo** [comment]
It's actually pretty hard to tell—you can check whether you have GStreamer and the appropriate Python bindings installed, and then it's likely that's what's happening.

**Comment by fpom** [comment]
I'm not sure but I think is is installed: the following does not fail

```
import gsi
gsi.require_version('Gst', '1.0') 
from gi.repository import Gst
```

So, since beetbox/audioread#84 has been fixed, my understanding is that the memory leak I've observed will be fixed in the next release?

**Comment by sampsyo** [comment]
Yep!

**Comment by fpom** [comment]
Nice ! :)
Thanks for your help.
