### ISSUE TITLE
Chromaprint not defined in windows

### ISSUE THREAD

**Issue by Alvarofg** [beetbox/pyacoustid#67]
Hi, I'm looking for a way to use this library in windows. When downloading from https://acoustid.org/chromaprint all I'm getting for windows is the utility `fpcalc.exe.` Which, I can use to generate fingerprints using `acoustid.fingerprint_file()` once I included it in the system path. 

However, when trying acoustid.fingerprint() I'm getting an     
```
fper = chromaprint.Fingerprinter()
NameError: name 'chromaprint' is not defined
...
except chromaprint.FingerprintError:
NameError: name 'chromaprint' is not defined
```

I'm thinking I have to do something extra to get actually install the chromaprint library. Any advise? 

Things I tried:
1. pip install chromaprint <-- It turns there is another unrelated package called chromaprint
2.  checked #44 fpcalc.exe is the `$PATH`

**Comment by sampsyo** [comment]
You'll need to `import chromaprint` to use the `chromaprint` module in Python.

**Comment by Alvarofg** [comment]
I ended up downloading the source code from https://github.com/acoustid/chromaprint.git and used VS 2019 Community to build it. I got a `chromaprint.dll` file which I moved into `$Path` . It seems to be working now

**Comment by sampsyo** [comment]
Great!
