### ISSUE TITLE
latest pip version does not include compare function

### ISSUE THREAD

**Issue by bindestriche** [beetbox/pyacoustid#80]
Installing the pip package to confirm the latest pull request, I noticed the compare function no not being present.
see  https://gist.github.com/bindestriche/06f9693c550ddabe4d1e3e7a557098fe

**Comment by sampsyo** [comment]
Indeed; we haven't released a new version for v1.3.0 yet. It's convenient that we delayed in order to find the bugs in #78… maybe it would be prudent to give it a moment to make sure we're confident in this state before we cut another release?

**Comment by bindestriche** [comment]
While I understand your reasoning, I think because we are not changing existing functionality, it is okay to make the feature available to a wider audience. We will not be breaking any existing codebases. The further spread will make it more likely to receive bug reports.

a --pre / pre-release package sounds like the right solution here.

**Comment by albertopasqualetto** [comment]
This issue has been solved and so should be closed.
